export * from './Layout/Layout'
export * from './Home/Home'
export * from './ClothesPage/ClothesPage'
export * from './Shop/Shop'
export * from './PageOfClothes/PageOfClothes'
export * from './Cart/Cart'
